FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore src/Web/Web.csproj

RUN dotnet publish src/Web/Web.csproj \
    --configuration Release \
    --output /app/publish \
    --no-restore \
    /p:SkipSpaBuild=true \
    /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

USER $APP_UID

ENTRYPOINT ["dotnet", "CleanArchitecture.Web.dll"]
