FROM node:22-alpine AS build

WORKDIR /app

COPY src/Web/ClientApp/package*.json ./

RUN npm ci

COPY src/Web/ClientApp/ ./

RUN npm run build -- --configuration production


FROM nginx:alpine AS runtime

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
