name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Show .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore CleanArchitecture.slnx

      - name: Build solution
        run: |
          dotnet build CleanArchitecture.slnx \
            --configuration Release \
            --no-restore
            
      - name: Install Playwright Chromium
        run: |
          pwsh ./artifacts/bin/Web.AcceptanceTests/release/playwright.ps1 install --with-deps chromium            
      

      - name: Run tests
        run: |
          dotnet test CleanArchitecture.slnx \
            --configuration Release \
            --no-build \
            --verbosity normal
            
  backend-image:
    name: Build Backend Docker Image
    needs: build-and-test
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show Git commit SHA
        run: |
          echo "Git SHA: ${GITHUB_SHA}"
          echo "Image: backend:${GITHUB_SHA}"

      - name: Build backend Docker image
        run: |
          docker build \
            --file Dockerfile.backend \
            --tag backend:${GITHUB_SHA} \
            .

      - name: Show backend Docker image
        run: |
          docker images backend:${GITHUB_SHA}
